import type { AskSource, CompareResult } from "@/lib/gemini";
import { SMART_TEMPLATES } from "@/lib/smart-templates";
import { jsPDF } from "jspdf";

export type ExportFormat = "md" | "txt" | "pdf";

export type ExportAnalysisKind =
  | "summary"
  | "ask"
  | "comparison"
  | "smart-summary"
  | "find-risks"
  | "explain-simply"
  | "action-items"
  | "key-questions"
  | "find-contradictions";

export type ExportDocument = {
  analysisTitle: string;
  analysisSlug: string;
  sourceDocuments: string[];
  generatedAt: string;
  /** Main result body (markdown-ish for headings/bullets). */
  body: string;
  /** Optional question shown for Ask / Quick Action exports. */
  question?: string;
  sources?: AskSource[];
};

type ContentBlock =
  | { type: "heading"; level: 1 | 2; text: string }
  | { type: "paragraph"; text: string }
  | { type: "bullet"; text: string };

function markdownToPlainText(content: string): string {
  return content
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/__(.*?)__/g, "$1")
    .replace(/_(.*?)_/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/^\s*[-*+]\s+/gm, "- ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export function sanitizeFilename(name: string, maxLength = 80): string {
  const sanitized = name
    .replace(/[<>:"/\\|?*\u0000-\u001F]/g, "-")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");

  if (!sanitized) {
    return "document";
  }

  return sanitized.slice(0, maxLength);
}

function stripPdfExtension(name: string): string {
  return name.replace(/\.pdf$/i, "");
}

function formatGeneratedAt(iso?: string): string {
  const date = iso ? new Date(iso) : new Date();
  if (Number.isNaN(date.getTime())) {
    return new Date().toISOString();
  }
  return date.toISOString();
}

function formatDisplayDate(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) {
    return iso;
  }
  return date.toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

const TEMPLATE_SLUGS: Record<string, string> = {
  "smart-summary": "summary",
  "find-risks": "risks",
  "explain-simply": "explain",
  "action-items": "action-items",
  "key-questions": "key-questions",
  "find-contradictions": "contradictions",
};

/** Resolve Quick Action title/slug from a prepared question, if it matches. */
export function resolveAskExportMeta(question: string): {
  analysisTitle: string;
  analysisSlug: string;
} {
  const trimmed = question.trim();
  for (const template of SMART_TEMPLATES) {
    if (template.prompt.trim() === trimmed) {
      return {
        analysisTitle: template.title,
        analysisSlug: TEMPLATE_SLUGS[template.id] ?? "analysis",
      };
    }
  }

  return {
    analysisTitle: "Custom AI Answer",
    analysisSlug: "analysis",
  };
}

export function getExportFilename(
  analysisSlug: string,
  sourceDocuments: string[],
  format: ExportFormat,
): string {
  const docPart =
    sourceDocuments.length > 1
      ? sourceDocuments.map((name) => sanitizeFilename(stripPdfExtension(name))).join("-vs-")
      : sanitizeFilename(stripPdfExtension(sourceDocuments[0] ?? "document"));

  const slug = sanitizeFilename(analysisSlug || "analysis");
  return `sumvora-${slug}-${docPart}.${format}`;
}

function formatBulletSection(
  title: string,
  items: string[],
  format: "md" | "txt",
): string {
  if (items.length === 0) {
    return format === "md"
      ? `## ${title}\n\nNone identified.\n`
      : `${title.toUpperCase()}\n\nNone identified.\n`;
  }

  if (format === "md") {
    return `## ${title}\n\n${items.map((item) => `- ${item}`).join("\n")}\n`;
  }

  return `${title.toUpperCase()}\n\n${items.map((item) => `- ${item}`).join("\n")}\n`;
}

function buildHeaderLines(doc: ExportDocument, format: "md" | "txt"): string {
  const documentsLine =
    doc.sourceDocuments.length > 0
      ? doc.sourceDocuments.join(" vs ")
      : "Unknown document";

  if (format === "md") {
    return [
      `# ${doc.analysisTitle}`,
      "",
      "**Generated by Sumvora**",
      "",
      `- Analysis: ${doc.analysisTitle}`,
      `- Document: ${documentsLine}`,
      `- Generated: ${formatDisplayDate(doc.generatedAt)}`,
      "",
    ].join("\n");
  }

  return [
    doc.analysisTitle.toUpperCase(),
    "",
    "Generated by Sumvora",
    "",
    `Analysis: ${doc.analysisTitle}`,
    `Document: ${documentsLine}`,
    `Generated: ${formatDisplayDate(doc.generatedAt)}`,
    "",
    "----------------------------------------",
    "",
  ].join("\n");
}

function buildSourcesSection(
  sources: AskSource[] | undefined,
  format: "md" | "txt",
): string {
  if (!sources || sources.length === 0) {
    return "";
  }

  if (format === "md") {
    const lines = sources.map(
      (source) => `- **Page ${source.page}**: "${source.excerpt}"`,
    );
    return `\n## Sources\n\n${lines.join("\n")}\n`;
  }

  const lines = sources.map(
    (source) => `- Page ${source.page}: "${source.excerpt}"`,
  );
  return `\nSOURCES\n\n${lines.join("\n")}\n`;
}

export function buildExportText(
  doc: ExportDocument,
  format: "md" | "txt",
): string {
  const header = buildHeaderLines(doc, format);
  const questionBlock =
    doc.question && doc.question.trim()
      ? format === "md"
        ? `## Question\n\n${doc.question.trim()}\n\n## Answer\n\n`
        : `QUESTION\n\n${doc.question.trim()}\n\nANSWER\n\n`
      : "";

  const body =
    format === "md" ? doc.body.trim() : markdownToPlainText(doc.body);

  return `${header}${questionBlock}${body}\n${buildSourcesSection(doc.sources, format)}`;
}

function parseContentBlocks(content: string): ContentBlock[] {
  const lines = content.replace(/\r\n/g, "\n").split("\n");
  const blocks: ContentBlock[] = [];
  let paragraph: string[] = [];

  const flushParagraph = () => {
    if (paragraph.length === 0) return;
    blocks.push({ type: "paragraph", text: paragraph.join(" ").trim() });
    paragraph = [];
  };

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();
    const trimmed = line.trim();

    if (!trimmed) {
      flushParagraph();
      continue;
    }

    const headingMatch = trimmed.match(/^(#{1,2})\s+(.+)$/);
    if (headingMatch) {
      flushParagraph();
      blocks.push({
        type: "heading",
        level: headingMatch[1].length === 1 ? 1 : 2,
        text: markdownToPlainText(headingMatch[2]),
      });
      continue;
    }

    const bulletMatch = trimmed.match(/^[-*+]\s+(.+)$/);
    if (bulletMatch) {
      flushParagraph();
      blocks.push({
        type: "bullet",
        text: markdownToPlainText(bulletMatch[1]),
      });
      continue;
    }

    paragraph.push(markdownToPlainText(trimmed));
  }

  flushParagraph();
  return blocks;
}

function downloadBlob(filename: string, blob: Blob): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

export function downloadFile(
  filename: string,
  content: string,
  format: Exclude<ExportFormat, "pdf">,
): void {
  const mimeType =
    format === "md" ? "text/markdown;charset=utf-8" : "text/plain;charset=utf-8";
  downloadBlob(filename, new Blob([content], { type: mimeType }));
}

function downloadPdfFromDocument(filename: string, doc: ExportDocument): void {
  const pdf = new jsPDF({ unit: "pt", format: "letter", compress: true });
  const marginX = 54;
  const marginY = 54;
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const maxWidth = pageWidth - marginX * 2;
  let y = marginY;

  const ensureSpace = (needed: number) => {
    if (y + needed <= pageHeight - marginY) return;
    pdf.addPage();
    y = marginY;
  };

  const writeWrapped = (
    text: string,
    options: { fontSize: number; fontStyle?: "normal" | "bold"; gapAfter?: number },
  ) => {
    const fontStyle = options.fontStyle ?? "normal";
    pdf.setFont("helvetica", fontStyle);
    pdf.setFontSize(options.fontSize);
    const lines = pdf.splitTextToSize(text, maxWidth) as string[];
    const lineHeight = options.fontSize * 1.35;

    for (const line of lines) {
      ensureSpace(lineHeight);
      pdf.text(line, marginX, y);
      y += lineHeight;
    }

    y += options.gapAfter ?? 8;
  };

  // Brand header
  writeWrapped("Sumvora", {
    fontSize: 11,
    fontStyle: "bold",
    gapAfter: 4,
  });
  writeWrapped(doc.analysisTitle, {
    fontSize: 18,
    fontStyle: "bold",
    gapAfter: 10,
  });

  const documentsLine =
    doc.sourceDocuments.length > 0
      ? doc.sourceDocuments.join(" vs ")
      : "Unknown document";

  writeWrapped(`Document: ${documentsLine}`, {
    fontSize: 10,
    gapAfter: 2,
  });
  writeWrapped(`Generated: ${formatDisplayDate(doc.generatedAt)}`, {
    fontSize: 10,
    gapAfter: 14,
  });

  // Divider
  ensureSpace(12);
  pdf.setDrawColor(199, 210, 254);
  pdf.setLineWidth(1);
  pdf.line(marginX, y, pageWidth - marginX, y);
  y += 16;

  if (doc.question?.trim()) {
    writeWrapped("Question", { fontSize: 13, fontStyle: "bold", gapAfter: 6 });
    writeWrapped(doc.question.trim(), { fontSize: 11, gapAfter: 12 });
    writeWrapped("Answer", { fontSize: 13, fontStyle: "bold", gapAfter: 6 });
  }

  const blocks = parseContentBlocks(doc.body);
  for (const block of blocks) {
    if (block.type === "heading") {
      writeWrapped(block.text, {
        fontSize: block.level === 1 ? 14 : 12,
        fontStyle: "bold",
        gapAfter: 8,
      });
      continue;
    }

    if (block.type === "bullet") {
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(11);
      const bulletIndent = 14;
      const lines = pdf.splitTextToSize(block.text, maxWidth - bulletIndent) as string[];
      const lineHeight = 11 * 1.35;
      for (let i = 0; i < lines.length; i += 1) {
        ensureSpace(lineHeight);
        if (i === 0) {
          pdf.text("•", marginX, y);
        }
        pdf.text(lines[i], marginX + bulletIndent, y);
        y += lineHeight;
      }
      y += 4;
      continue;
    }

    writeWrapped(block.text, { fontSize: 11, gapAfter: 10 });
  }

  if (doc.sources && doc.sources.length > 0) {
    writeWrapped("Sources", { fontSize: 13, fontStyle: "bold", gapAfter: 6 });
    for (const source of doc.sources) {
      writeWrapped(`Page ${source.page}: "${source.excerpt}"`, {
        fontSize: 10,
        gapAfter: 6,
      });
    }
  }

  // Footer page numbers
  const pageCount = pdf.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    pdf.setPage(page);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(100);
    pdf.text(
      `Sumvora · Page ${page} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 28,
      { align: "center" },
    );
    pdf.setTextColor(0);
  }

  downloadBlob(filename, pdf.output("blob"));
}

export function downloadExportDocument(
  doc: ExportDocument,
  format: ExportFormat,
): void {
  const filename = getExportFilename(
    doc.analysisSlug,
    doc.sourceDocuments,
    format,
  );

  if (format === "pdf") {
    downloadPdfFromDocument(filename, doc);
    return;
  }

  downloadFile(filename, buildExportText(doc, format), format);
}

export function buildSummaryExportDocument(options: {
  summary: string;
  fileName: string;
  generatedAt?: string;
}): ExportDocument {
  return {
    analysisTitle: "AI Summary",
    analysisSlug: "summary",
    sourceDocuments: [options.fileName],
    generatedAt: formatGeneratedAt(options.generatedAt),
    body: options.summary.trim(),
  };
}

export function buildAskExportDocument(options: {
  question: string;
  answer: string;
  fileName: string;
  sources?: AskSource[];
  generatedAt?: string;
  analysisTitle?: string;
  analysisSlug?: string;
}): ExportDocument {
  const meta = resolveAskExportMeta(options.question);
  return {
    analysisTitle: options.analysisTitle ?? meta.analysisTitle,
    analysisSlug: options.analysisSlug ?? meta.analysisSlug,
    sourceDocuments: [options.fileName],
    generatedAt: formatGeneratedAt(options.generatedAt),
    question: options.question,
    body: options.answer.trim(),
    sources: options.sources,
  };
}

export function buildCompareExportDocument(options: {
  result: CompareResult;
  documentNames: string[];
  generatedAt?: string;
}): ExportDocument {
  const body = [
    "## Executive Summary",
    "",
    options.result.executiveSummary.trim(),
    "",
    formatBulletSection("Similarities", options.result.similarities, "md"),
    formatBulletSection("Differences", options.result.differences, "md"),
    formatBulletSection("Contradictions", options.result.contradictions, "md"),
    formatBulletSection("Key Facts", options.result.keyFacts, "md"),
    "## Sources",
    "",
    options.result.sources.length > 0
      ? options.result.sources
          .map(
            (source) =>
              `- **${source.documentName}** (Page ${source.page}): "${source.excerpt}"`,
          )
          .join("\n")
      : "None identified.",
    "",
  ].join("\n");

  return {
    analysisTitle: "Document Comparison",
    analysisSlug: "comparison",
    sourceDocuments: options.documentNames,
    generatedAt: formatGeneratedAt(options.generatedAt),
    body,
  };
}

/** @deprecated Prefer downloadExportDocument — kept for call-site clarity. */
export function downloadSummaryExport(options: {
  summary: string;
  fileName: string;
  format: ExportFormat;
  generatedAt?: string;
}): void {
  downloadExportDocument(buildSummaryExportDocument(options), options.format);
}

export function downloadAskExport(options: {
  question: string;
  answer: string;
  fileName: string;
  sources?: AskSource[];
  format: ExportFormat;
  generatedAt?: string;
}): void {
  downloadExportDocument(buildAskExportDocument(options), options.format);
}

export function downloadCompareExport(options: {
  result: CompareResult;
  documentNames: string[];
  format: ExportFormat;
  generatedAt?: string;
}): void {
  downloadExportDocument(buildCompareExportDocument(options), options.format);
}
